name: "Post-Integration: Regression Test"

on:
  push:
    branches: [ $default-branch ]

  workflow_dispatch:

env:
  MAVEN_OPTS: "-Djansi.force=true"
  # Repository of regression test in format <organization>/<repository>.
  REPOSITORY: ""
  # Maven project under monorepo of regression test.
  PROJECT: ""

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - name: Check if variable is empty
        run: |
          if [ -z "${REPOSITORY}" ]; then
            echo "::error::'REPOSITORY' environment variable must be set"
            exit 1
          fi
          if [ -z "${PROJECT}" ]; then
            echo "::error::'PROJECT' environment variable must be set"
            exit 1
          fi

      - uses: actions/checkout@v2
        with:
          repository: ${{ env.REPOSITORY }}
          ref: master
          token: ${{ secrets.REGRESSION_PAT }}

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml', '${{ env.PROJECT }}/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - run: mvn -pl ${PROJECT} test -ntp
      - run: mvn -pl ${PROJECT} verify -ntp
