on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          repository: sepulsa/qcr-sepulsa
          ref: master
          token: ${{ secrets.REGRESSION_PAT }}
